swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  # Endpoint pour la connexion des utilisateurs
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # Endpoint pour l'inscription des utilisateurs
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # Endpoints pour récupérer et mettre à jour le profil utilisateur
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      produces:
       - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    # Endpoint pour mettre à jour le username (devrait plutôt être patch)
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # Endpoint pour récupérer la liste des comptes
  /comptes:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Obtenir tous les comptes avec leurs soldes
      description: API pour récupérer tous les comptes avec leurs soldes pour le mois en cours.
      produces:
        - application/json
      responses:
        '200':
          description: Récupération réussie des comptes.
          schema:
            type: array
            items:
              $ref: '#/definitions/Compte'
        '400':
          description: Requête invalide.
        '500':
          description: Erreur interne du serveur


  # Endpoint pour récupérer le détail des transactions d'un compte
  /comptes/{compteId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Récupérer les détails des transactions d'un compte
      description: API pour récupérer les détails des transactions pour un compte spécifique.
      parameters:
          - name: compteId
            in: path
            required: true
            type: string
            description: Id du compte.
      produces:
        - application/json
      responses:
        '200':
          description: Détails des transactions récupérés avec succès
          schema:
            $ref: '#/definitions/TransactionDetail'
        '400':
          description: ID du compte invalide.
        '404':
          description: Compte non trouvé
        '500':
          description: Erreur interne du serveur
  
    # Endpoint pour mettre à jour une transaction
    patch:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Modifier les informations d'une transaction
      description: API pour modifier les informations d'une transaction, comme la catégorie ou les notes.
      parameters:
        - in: path
          name: compteId
          type: string
          required: true
          description: "ID du compte auquel appartient la transaction."
        - in: path
          name: transactionId
          type: string
          required: true
          description: "ID de la transaction à mettre à jour."
        - in: body
          name: transaction
          description: Objet contenant les détails à mettre à jour
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction mise à jour avec succès
        '400':
          description: Paramètres de requête invalides
        '404':
          description: Transaction non trouvée
        '500':
          description: Erreur interne du serveur

  # Endpoint pour récupérer la liste des catégories disponibles
  /categories:
    get:
      tags:
        - Transactions Module
      summary: Récupérer toutes les catégories
      description: Retourne une liste des catégories disponibles pour les transactions.
      produces:
        - application/json
      responses:
        '200':
          description: Liste des catégories récupérée avec succès
          schema:
            type: array
            items:
              type: string
        '500':
          description: Erreur interne du serveur

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Compte:
    type: object
    properties:
      compteId:
        type: string
        description: L'identifiant unique du compte.
      nomCompte:
        type: string
        description: Le nom du compte (par exemple, "Argent Bank Checking").
      soldeDisponible:
        type: number
        format: float
        description: Le solde disponible sur le compte.

  TransactionDetail:
    type: object
    properties:
      id:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: double
      balance:
        type: number
        format: double
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: "Catégorie de la transaction récupérée à partir de l'endpoint /categories"
      notes:
        type: string
